### ISSUE TITLE
[BUG] Invalid buffer ID when leaving `vim.ui.input`

### ISSUE THREAD

**Issue by mediumrarez** [Pocco81/auto-save.nvim#46]
Symptoms: error message when exiting `vim.ui.input` prompt.

Steps to reproduce: 
1. Install `auto-save.nvim`
2. Run `:lua vim.ui.input({}, function() end)`
3. Observe error thrown

![error](https://user-images.githubusercontent.com/59168253/184059274-4474babc-4a4b-4da1-9aff-7e05623ab44d.png)

**Comment by XXiaoA** [comment]
Same bug!

**Comment by XXiaoA** [comment]
> Symptoms: error message when exiting `vim.ui.input` prompt.
> 
> Steps to reproduce:
> 
> 1. Install `auto-save.nvim`
> 2. Run `:lua vim.ui.input({}, function() end)`
> 3. Observe error thrown
> 
> ![error](https://user-images.githubusercontent.com/59168253/184059274-4474babc-4a4b-4da1-9aff-7e05623ab44d.png)

I have fixed it in my [fork](https://github.com/XXiaoA/auto-save.nvim/commit/9dac4e80c79f9e3afc662153987bb0f4efa99372). Welcome to try my fork 😀

**Comment by fraidev** [comment]
@XXiaoA Thank you. Your fork resolved for me as well.

**Comment by drinkitup777** [comment]
@XXiaoA Tested and working fine. Time for a pull request?

**Comment by XXiaoA** [comment]
> @XXiaoA Tested and working fine. Time for a pull request?

[PR](https://github.com/Pocco81/auto-save.nvim/pull/47) has been created. But i'm not sure the author will merge it or not. Because I format the file with my own .stylua.toml

**Comment by fragov** [comment]
Is there any reason, why this annoying bug still not fixed? 

Has someone found a solution for this using setup config? I constantly get this error when I create new files and folders in NvimTree and also when I rename variables using LSP.

**Comment by primeapple** [comment]
There are several PRs addressing this issue. Can we please merge one of them. It's just a click on merge...

**Comment by gegnew** [comment]
another bump for this to get merged

**Comment by dlip** [comment]
Yes please, this is driving me nuts
